server:
  #Jetty默认是非阻塞的，可以处理更多并发请求
  jetty:
    threads:
    #acceptors线程接收http  请求
      acceptors: 4
    #selectors 线程池负责处理HTTP消息协议数据包
      selectors: 8
    #worker线程池负责调用web方法
      min: 8
      max: 200
  port: 8092
  servlet:
    context-path: /hospital-api

spring:
  datasource:
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://47.108.146.141:8765;serialization=PROTOBUF
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-on-borrow: true
      test-while-idle: true
      max-active: 8
      min-idle: 4
      validation-query: SELECT 1

  servlet:
    multipart:
      enabled: true
      #上传的文件不能超过20m
      max-file-size: 20MB
      #http请求不能超过20M
      max-request-size: 20MB

  redis:
    database: 0
    host: 47.108.146.141
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8

  quartz:
    job-store-type: memory

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.hospital.api.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.hospital.api.db.dao: warn
  pattern:
    console: "%d{yyyy/MM/dd HH:mm:ss}  %-5level  %msg%n"

sa-token:
  #http请求头中token的名称
  token-name: token
  #token有效期，单位s，默认30天，-1代表永不过期
  timeout: 2592000
  #token临时有效期
  activity-timeout: -1
  #是否允许同一账号并发登录
  allow-concurrent-login: true
  #在多人登录同一账号时，是否共用一个token
  is-share: false
  #token的风格
  token-style: uuid
  #读取Cookie中Token
  isReadCookie: false


#wechat:
#  app-id: 你的微信小程序APPID
#  app-secret: 你的微信小程序密钥
#  pay:
#    v3:
#      patient-wx-api:
#        app-id: 你的微信小程序APPID
#        app-v3-secret: 微信商户平台密钥
#        mch-id: 微信商户平台ID
#        domain: http://内网穿透的外网IP地址和端口/hospital-wx-api
#        cert-path: apiclient_cert.p12

#tencent:
#  cloud:
#    appId: 你的腾讯云APPID
#    secretId: 你的腾讯云secretId
#    secretKey: 你的腾讯云secretKey
#    face:
#      groupName: hospital
#      region: ap-beijing
#  trtc:
#    appId: TRTC的appId
#    secretKey: TRTC的secretKey
#    expire: 86400

minio:
  endpoint: http://47.108.146.141:9000
  access-key: root
  secret-key: abc123456

